
version: 1.0.{build}

image:
  - Visual Studio 2017
  - Ubuntu1604

platform:
  - x64

environment:
  QT_DIR_WIN_64: C:\Qt\5.12.6\msvc2017_64
  QT_DIR_WIN_32: C:\Qt\5.12.6\msvc2017

for:
-
  matrix:
    only:
      - image: Visual Studio 2017

  init:
    - ver
    - cmake --version

  build_script:
    - ps: ./build.ps1

  artifacts:
    - path: bin_msvc15_x64
      type: zip
      name: App-msvc15-x64

    - path: bin_msvc15_x86
      type: zip
      name: App-msvc15-x86
-
  matrix:
    only:
      - image: Ubuntu1604

  init:
    - cmake --version
    - gcc -v

  install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get -y install qtbase5-dev libqt5svg5-dev qt5-default
    - mkdir tools && cd tools
    # we use wget to fetch the cmake binaries
    - wget --no-check-certificate https://cmake.org/files/v3.17/cmake-3.17.1-Linux-x86_64.tar.gz
    - wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
    - wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
    # extract the binaries; the output here is quite lengthy,
    # so we swallow it to not clutter up the console
    - tar -xvf cmake-3.17.1-Linux-x86_64.tar.gz > /dev/null
    - mv cmake-3.17.1-Linux-x86_64 cmake-install
    - chmod a+x linuxdeploy-x86_64.AppImage linuxdeploy-plugin-qt-x86_64.AppImage
    # add both the top-level directory and the bin directory from the archive
    # to the system PATH. By adding it to the front of the path we hide the
    # preinstalled CMake with our own.
    - cd ..
    - PATH=tools/cmake-install:tools/cmake-install/bin:$PATH
    - cmake --version
#    - sh: sudo apt-get -y install -qq gcc g++ cmake

  build_script:
    - echo Ubuntu build script
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
    - make
    - make install DESTDIR=AppDir
    - ../tools/linuxdeploy-x86_64.AppImage --appdir AppDir --plugin qt --output appimage
    - mv AppTest*.AppImage AppTest-x86_64.AppImage
    - cd ..

  artifacts:
    - path: build/AppTest-x86_64.AppImage
      type: File
      name: AppTest-x86_64.AppImage


deploy:
  release: CmakeCITest-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: 6xHQBZVK+RtxmddurGPIg7Kx5vecSN1vVxwbv35EQmsIey4DXDXYhwAW/yLXbNLJ
  artifact: App-msvc15-x64, App-msvc15-x86, AppTest-x86_64.AppImage
  draft: false
  prerelease: false
  tag: $(APPVEYOR_REPO_TAG_NAME)
  on:
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
