os: Visual Studio 2015

build_script:
  - md build
  - cd build
  - cmake -DQT_WIN_PATH=C:\Qt\5.13.2\msvc2015_64 -G "Visual Studio 14 2015 Win64" ..
  - cmake --build . --config Release
  - cd ..

artifacts:
  - path: build
    name: build\Release\cmake-test.exe
