os: Visual Studio 2015

build_script:
  - md build
  - cd build
  - cmake -DQT_WIN_PATH=C:\Qt\5.13.2\msvc2015_64 -G "Visual Studio 14 2015 Win64" ..
  - cmake --build . --config Release
  - cd ..
  - md bin
  - md bin\platforms
  - md bin\styles
  - copy build\Release\cmake_test.exe bin\cmake_test.exe
  - copy C:\Qt\5.13.2\msvc2015_64\bin\Qt5Core.dll bin\Qt5Core.dll
  - copy C:\Qt\5.13.2\msvc2015_64\bin\Qt5Gui.dll bin\Qt5Gui.dll
  - copy C:\Qt\5.13.2\msvc2015_64\bin\Qt5Widgets.dll bin\Qt5Widgets.dll
  - copy C:\Qt\5.13.2\msvc2015_64\plugins\platforms\qwindows.dll bin\platforms\qwindows.dll
  - copy C:\Qt\5.13.2\msvc2015_64\plugins\styles\qwindowsvistastyle.dll bin\styles\qwindowsvistastyle.dll

artifacts:
  - path: bin
    type: zip
    name: App
