language: cpp
os: linux
dist: xenial

compiler:
  - gcc

# the install step will take care of deploying a newer cmake version
install:
  # first we create a directory for the CMake binaries
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  # we use wget to fetch the cmake binaries
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.17/cmake-3.17.1-Linux-x86_64.tar.gz
  # this is optional, but useful:
  # do a quick md5 check to ensure that the archive we downloaded did not get compromised
  - echo "07D988E7144C435A525621C9CDEA6245 *cmake-3.17.1-Linux-x86_64.tar.gz" > cmake_md5.txt
  - md5sum -c cmake_md5.txt
  # extract the binaries; the output here is quite lengthy,
  # so we swallow it to not clutter up the travis console
  - tar -xvf cmake-3.17.1-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.17.1-Linux-x86_64 cmake-install
  # add both the top-level directory and the bin directory from the archive
  # to the system PATH. By adding it to the front of the path we hide the
  # preinstalled CMake with our own.
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  # don't forget to switch back to the main build directory once you are done
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build
  # run cmake; here we assume that the project's
  # top-level CMakeLists.txt is located at '..'
  - cmake -DCMAKE_BUILD_TYPE=Release ..

script:
  # once CMake has done its job we just build using make as usual
  - cmake --build . --target cmake_test

deploy:
  provider: releases
  token:
    secure: "vJmz+eNqWt2gEcbdynteKgy1CQq/L2BW0o5IaQTZoFcpOXz4wurPJwwFNezisaT/OApXNpqbspCu0SocEQyRvuEnZPFthEbu4y9+ICBF6hZG+cin7NIQAKCaz5341wDsFjQGLyuukVoEIEyJ17Gl0+FVnrpePwLPWF6wyw7nPAx9oeWRCrx7TEE0bdy3HOxwX8Y7/JcWE4Ur30hXyDx1CzI3coUseE1MBkuOZJIwYFbqQJxDgXJio485u2CDXVgTDYCTti9THMiF67/i4W5SMV17PRslRVZIZSOOTz2Ovbz27YDr58xd22FI0qoOZ+Aza5LuzKyh4/dHXLdB5WwmPrKrxyPwssGIL7UYsUd81KXjkkhhTPhTrLmp5vAiDVYyXIGmonuOiZ8A7uvmwiOh4CaJcOKLI5Hdx+9ZZ25Nx3LxGEUBKp16XCAma2d+FF8X/AE/dghjPX2F+bpXZNjsEZw7VkUHq+eCXTpb0TW8MIKVsnKaZaKCJKSlgsw26+ir06N44UH1/0Dvnd+Sii0qm1Bu2Qkw/HXkLZR1/rPKYsnJZOiZARfo9636Qt1R4q2hiHLZb3LKfIQMvatE11+/vuI1DmwLhb9zYEp5/lBHTSCklZu+N4Qqmvf16gI19hNnsg/lyRoYm5F4MNW6qylECPgXAk209CLNvTxYcjM6DmA="
  file: "cmake_test"
  cleanup: false
  draft: true
  overwrite: true
#  on:
#    tags: true
